# Altere 'seu_banco' para o nome do banco que você criou no MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/projeto_defeso?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Esta linha faz a mágica de criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true